# Generated by Django 4.1.3 on 2022-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='estrellas',
            field=models.IntegerField(),
        ),
    ]
