# Generated by Django 4.1.3 on 2023-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0005_receta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Recetas'),
        ),
    ]
