# Generated by Django 4.1.3 on 2023-01-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0007_alter_receta_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='img',
        ),
    ]
