# Generated by Django 4.1.3 on 2023-01-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0011_alter_imagen_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_receta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capuchino.receta'),
        ),
    ]
