# Generated by Django 4.1.3 on 2023-01-02 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Capuchino', '0012_alter_imagen_receta_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Avatares'),
        ),
        migrations.CreateModel(
            name='Pepito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
