# Generated by Django 4.1.3 on 2023-01-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0013_alter_imagen_receta_imagen_pepito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pepito',
        ),
    ]
