# Generated by Django 4.1.3 on 2023-01-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0014_delete_pepito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen_receta',
            old_name='receta',
            new_name='user',
        ),
    ]
