# Generated by Django 4.1.3 on 2023-01-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0015_rename_receta_imagen_receta_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen_receta',
            old_name='user',
            new_name='recetita',
        ),
    ]
