# Generated by Django 4.1.3 on 2023-01-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0016_rename_user_imagen_receta_recetita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen_receta',
            old_name='recetita',
            new_name='receta',
        ),
    ]
