# Generated by Django 4.1.3 on 2023-01-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0018_receta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen_receta',
            old_name='receta',
            new_name='nombre',
        ),
    ]
