# Generated by Django 4.1.3 on 2023-01-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0020_rename_nombre_imagen_receta_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
        migrations.DeleteModel(
            name='Imagen_receta',
        ),
    ]
