# Generated by Django 4.1.3 on 2023-01-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0021_remove_receta_imagen_delete_imagen_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
