# Generated by Django 4.1.3 on 2023-01-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0022_alter_receta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
