# Generated by Django 4.1.3 on 2023-01-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capuchino', '0025_alter_receta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='fecha',
        ),
        migrations.AddField(
            model_name='receta',
            name='dia',
            field=models.CharField(default='2023/01/02', max_length=50),
        ),
    ]
